#!/usr/bin/env bash
# Sync proto sources into the self-contained Hugging Face Space folder.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/proto"
DST="$ROOT/space/orbital-braille"

mkdir -p "$DST"
rm -rf "$DST/orbital_braille"

COMMIT="$(git -C "$ROOT" rev-parse --short HEAD)"
UPDATED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$SRC/build_info.py" <<EOF
"""Auto-generated by scripts/sync_hf_space.sh — do not edit by hand."""

BUILD_COMMIT = "$COMMIT"
BUILD_UPDATED_UTC = "$UPDATED"
EOF

cp -r "$SRC/orbital_braille" "$DST/"
cp "$SRC/demo_core.py" "$DST/"
cp "$SRC/stov_analyzer.py" "$DST/"
cp "$SRC/build_info.py" "$DST/"
cp "$SRC/gradio_demo.py" "$DST/app.py"
# HF Spaces requirements — do NOT pin gradio here; HF installs gradio[oauth] from
# README sdk_version automatically. Pinning gradio in requirements.txt causes
# "Cannot install gradio==5.12.0 and gradio==5.27.0" build failures.
# pydantic==2.10.6 fixes gradio_client bool-schema crash; app.py also patches it.
cat > "$DST/requirements.txt" <<'EOF'
numpy>=1.24.0,<3.0.0
scipy>=1.10.0
matplotlib>=3.7.0
scikit-learn>=1.3.0
Pillow>=10.0.0
plotly>=5.18.0
pydantic==2.10.6
requests>=2.31.0
audioop-lts>=0.2.1; python_version >= "3.13"
EOF

{
  cat <<'EOF'
---
title: Orbital Braille VQC Typehead
emoji: 🔤
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 5.12.0
python_version: 3.12
app_file: app.py
pinned: false
license: cc-by-nc-sa-4.0
short_description: Orbital Braille VQC Typehead — browser demo
---

EOF
  cat "$ROOT/docs/HF_SPACE_README.md"
} > "$DST/README.md"

echo "Synced → $DST"
ls -la "$DST"